version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - app-network

  springboot-with-mongodb-container-one:
    image: mtiriwissem/java-app
    ports:
      - 8090:8081
    depends_on:
      mongo:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge